name: luotest
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  lpinyin: ^1.0.6
    # Dart 常用工具类库 https://github.com/Sky24n/common_utils
  common_utils: ^1.0.9
    # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^0.1.9
    # Flutter 国际化/多语言库 https://github.com/Sky24n/fluintl
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  # 汉字转拼音库 https://github.com/flutterchina/lpinyin
  # video_player: ^0.10.0+8
  image_picker: ^0.4.12+1
  flutter_screenutil: ^0.4.2
  web_socket_channel: ^1.0.12
  fluttertoast: ^2.2.11
  english_words: ^3.1.0
  # flutter_webview_plugin: "^0.3.0+2"
  groovin_material_icons: ^1.1.5
  http: '>=0.11.3+12'
  animated_text_kit: ^1.2.0
  flutter_slidable: ^0.4.9
  shimmer: ^1.0.0
  dio: ^1.0.13
  fluro: ^1.4.0
  timeago: ^2.0.10
  scoped_model: ^1.0.1
  event_bus: ^1.0.1
  flutter_spinkit: ^3.0.0
  cached_network_image: ^0.5.1
  flutter_staggered_grid_view: ^0.2.6
  flutter_custom_clippers: ^0.1.5
  video_player: ^0.10.0+2
  pull_to_refresh: ^1.1.6
  chewie: ^0.9.7
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - images/beijing2.jpg
    - images/beijing1.png
    - images/qidong.jpg
    - images/icon1.png
    - images/login_logo.png
    - assets/images/icon_home_tab.png
    - assets/images/icon_home_tab_pressed.png
    - assets/images/icon_popular_tab.png
    - assets/images/icon_popular_tab_pressed.png
    - assets/images/icon_movie_tab.png
    - assets/images/icon_movie_tab_pressed.png
    - assets/images/icon_mine_tab.png
    - assets/images/icon_mine_tab_pressed.png
    - assets/images/icon_empty.webp
    - assets/images/icon_load_error.png
    - assets/images/icon_placeholder.png
    - assets/images/icon_default_avatar.png
    - assets/images/icon_videodetail_num.png
    - assets/images/icon_videodetail_jishu.png
    - assets/images/icon_videodetail_name.png
    - assets/images/icon_videodetail_playlist.png
    - assets/images/icon_videodetail_director.png
    - assets/images/icon_videodetail_starring.png
    - assets/images/icon_videodetail_desc.png

  fonts:
    - family: HanaleiFill
      fonts:
        - asset: fonts/HanaleiFill-Regular.ttf
    - family: lishu
      fonts:
        - asset: fonts/lishu.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
